<p>&nbsp;</p>
<p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-family: arial,helvetica,sans-serif;"><span style="color: #000000; font-size: 14pt;"><strong>Indiana</strong></span><span style="color: #000000; font-size: 12pt;"><strong><br /></strong></span></span></p>
<hr /><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; line-height: 115%; color: #c00000;">Check the Device Status <br /><br /></span></strong></span>
<ul style="margin-top: 0in;" type="disc">
<li><span style="color: #000000; font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt; line-height: 115%;">Open Door: </span><span style="font-size: 10pt; line-height: 115%;">make sure once the retailer turns the lock handle and it pops out that the key is removed. This will prevent using the key to maneuver the lock handle which may cause the key to break. <br /><br /></span></span></li>
<li><span style="font-size: 10pt; line-height: 115%; color: #000000; font-family: arial,helvetica,sans-serif;">Advise retailer to sign in to the terminal Via Touch Screen<br /><br /></span></li>
<li><span style="color: #000000; font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt; line-height: 115%;">Select “</span><span style="font-size: 10pt; line-height: 115%;">Tools and services” from sub menu<br /></span></span></li>
</ul>
<ul style="margin-top: 0in;" type="disc">
<li><span style="color: #000000; font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt; line-height: 115%;">Select “Device Status”: </span><span style="font-size: 10pt; line-height: 115%;">check to make sure all devices are online, if not trouble shoot what ever is offline</span></span></li>
</ul>
<hr /><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; color: #c00000;">No Read-Intermittent Read<br /><br /></span></strong></span>
<p style="margin-right: -.7pt; line-height: normal;"><span style="font-size: 10pt; color: #000000; font-family: arial,helvetica,sans-serif;">1. Have retailer check visible connections on cord.</span></p>
<p style="margin-right: -.7pt; line-height: normal;"><span style="font-size: 10pt; color: #000000; font-family: arial,helvetica,sans-serif;">2. Reset the Gemini.</span></p>
<hr /><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; color: #c00000;">If not performing retailer functions<br /><br /></span></strong></span>
<ul>
<li style="margin-right: -.7pt; text-indent: -.25in; line-height: normal;"><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt;">&nbsp;<span style="font-style: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal; font-feature-settings: normal; font-language-override: normal; font-kerning: auto; font-synthesis: weight style; font-variant: normal;"> &nbsp;&nbsp;&nbsp;<span style="color: #000000;">&nbsp;&nbsp;&nbsp; </span></span></span><span style="color: #000000;"></span><span style="font-size: 10pt;"><span style="color: #000000;">If the display screen seems to be locked up, reset the Gemini</span>.</span></span></li>
</ul>
<hr /><span style="font-size: 12pt; font-family: arial,helvetica,sans-serif;"><strong><span style="color: #c00000;">Door/Hand Held Barcode Scanner<br /><br /></span></strong></span>
<p style="margin-right: -.7pt; line-height: normal;"><span style="font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="images/igt/in_lvm_bcs/image002.jpg" alt="Barcode scanner" width="334" height="251" /><strong><span style="text-decoration: underline;"><span style="font-size: 16pt;"><br /></span></span></strong></span></p>
<hr /><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; color: #c00000;">No Read-Intermittent Read<br /></span></strong></span><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; color: #c00000;"><br /></span></strong></span>
<p style="text-indent: -.25in; line-height: normal; margin: 0in -.7pt 10pt .25in;"><span style="font-family: arial,helvetica,sans-serif;"><span style="color: #000000;"><span style="font-size: 10pt;">1.<span style="font-style: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal; font-feature-settings: normal; font-language-override: normal; font-kerning: auto; font-synthesis: weight style; font-variant: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt;">Make sure players are holding the tickets within the correct range. </span></span></span></p>
<p style="text-indent: -.25in; line-height: normal; margin: 0in -.7pt 10pt .25in;"><span style="color: #000000; font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt;">2.<span style="font-style: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal; font-feature-settings: normal; font-language-override: normal; font-kerning: auto; font-synthesis: weight style; font-variant: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt;">Depending on the size of the barcode the ticket may need to be held closer or farther away. The ticket should be raised or lowered under the beam until the barcode registers.</span></span></p>
<p style="text-indent: -.25in; line-height: normal; margin: 0in -.7pt 10pt .25in;"><span style="color: #000000; font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt;">3.<span style="font-style: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal; font-feature-settings: normal; font-language-override: normal; font-kerning: auto; font-synthesis: weight style; font-variant: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt;">Reset the Gemini if issue not resolved.</span></span></p>
<hr /><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; color: #c00000;">Damaged</span></strong></span>
<ul>
<li style="margin-right: -.7pt; text-indent: -.25in; line-height: normal;"><span style="font-family: arial,helvetica,sans-serif;"><span style="color: #000000;"><span style="font-size: 10pt;"><span style="font-style: normal; font-weight: normal; font-size: 7pt; line-height: normal; font-size-adjust: none; font-stretch: normal; font-feature-settings: normal; font-language-override: normal; font-kerning: auto; font-synthesis: weight style; font-variant: normal;">&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt;">Note type and extent of damage</span></span></span></li>
</ul>
<div style="margin-bottom: 10pt;"><hr /><span style="font-family: arial,helvetica,sans-serif;"><strong><span style="font-size: 12pt; line-height: 115%; color: #c00000;">Site Specific</span></strong></span></div>
<p><span style="color: #000000; font-family: arial,helvetica,sans-serif;"><strong>IN<br /></strong></span></p>
<ul>
<li><span style="font-family: arial,helvetica,sans-serif;"><span style="color: #000000;"></span><span style="font-size: 10pt;"><span style="color: #000000;">If Barcode Scanner is not working – Dispatch</span> <strong><span style="color: #00b050;">UP</span></strong></span></span></li>
</ul>
</div>]]>